/*
    View: Text lang
*/

#ifndef _view_text_lang_H
#define _view_text_lang_H

#include "../../def.h"
#include <stdint.h>
#include <clib/u8g2.h>
extern const uint8_t u8g2_font_robotobd_08_tx[] U8G2_FONT_SECTION("u8g2_font_robotobd_08_tx");

//#define menuFont        u8g2_font_6x12_t_cyrillic
#define menuFont        u8g2_font_robotobd_08_tx
#define drawTxt         drawUTF8
#define getTxtWidth     getUTF8Width

#define TXT_MENU_EXIT               "> выход"
#define TXT_MENU_HOLD3SEC           "Удерж кнопку 3 сек"

#define TXT_MENU_CONFIG_SAVEERROR   "Ошибка сохранения"

#define TXT_MENU_ON                 "вкл"
#define TXT_MENU_OFF                "выкл"
#define TXT_MENU_YES                "да"
#define TXT_MENU_NO                 "нет"
#define TXT_MENU_OK                 "OK"
#define TXT_MENU_FAIL               "ошибка"
#define TXT_MENU_DISABLE            "выкл"

#define TXT_MENU_MAINPAGE_NONE      "не менять"
#define TXT_MENU_MAINPAGE_LAST      "предыдущая"
#define TXT_MENU_MAINPAGE_ALTNAV    "Нав+Высот"
#define TXT_MENU_MAINPAGE_ALT       "Высотомер"
#define TXT_MENU_MAINPAGE_NAV       "Навигация"
#define TXT_MENU_MAINPAGE_NAVPATH   "Путь"

#define TXT_MENU_POINT_CURRENT      "Выбранная точка"
#define TXT_MENU_POINT_NOTUSED      " (нет)"
#define TXT_MENU_POINT_NOCURR       "[без точки]"
#define TXT_MENU_POINT_SAVE         "Сохранить коорд."
#define TXT_MENU_POINT_NOTSELECT    "Точка не выбрана"
#define TXT_MENU_POINT_NONAV        "Нет NAVI спутников"
#define TXT_MENU_POINT_EEPROMFAIL   "Ошибка сохранения"
#define TXT_MENU_POINT_SAVED        "Точка сохранена"
#define TXT_MENU_POINT_CLEAR        "Очистить точку"
#define TXT_MENU_POINT_CLEARED      "Точка очищена"

#define TXT_MENU_DISPLAY_LIGHT      "Подсветка"
#define TXT_MENU_DISPLAY_CONTRAST   "Контраст"
#define TXT_MENU_DISPLAY_FLIPP180   "Развернуть на 180"

#define TXT_MENU_GND_MANUALSET      "Сбросить вручную"
#define TXT_MENU_GND_MANUALNOTALLOW "Ручной сброс запрещён"
#define TXT_MENU_GND_CORRECTED      "Уровень земли установлен"
#define TXT_MENU_GND_MANUALALLOW    "Разрешение ручн. сбр."
#define TXT_MENU_GND_AUTOCORRECT    "Автоподстройка"
#define TXT_MENU_GND_CORRECTONGND   "На земле"
#define TXT_MENU_GND_ALTCORRECT     "Превышение площадки"

#define TXT_MENU_AUTOMAIN_FF        "Своб. падение"
#define TXT_MENU_AUTOMAIN_CNP       "После раскрытия"
#define TXT_MENU_AUTOMAIN_LAND      "При приземлении"
#define TXT_MENU_AUTOMAIN_ONGND     "Долго на земле"
#define TXT_MENU_AUTOMAIN_POWERON   "При включении"

#define TXT_MENU_POWEROFF_FORCE     "Выключить вручную"
#define TXT_MENU_POWEROFF_NOFLY     "Без взлётов"
#define TXT_MENU_POWEROFF_AFTON     "После включения"

#define TXT_MENU_NAVON_CURRENT      "Текущее состояние"
#define TXT_MENU_NAVON_POWERON      "Вкл. при включении"
#define TXT_MENU_NAVON_TRKREC       "Вкл. при записи трека"
#define TXT_MENU_NAVON_TAKEOFF      "Вкл. на высоте"
#define TXT_MENU_NAVON_OFFLAND      "Выключать при приземлении"

#define TXT_MENU_NAV_GNSS           "Режим"
#define TXT_MENU_NAV_GNSS_GLONASS   "GLONASS"
#define TXT_MENU_NAV_GNSS_GPS       "GPS"
#define TXT_MENU_NAV_GNSS_GLONGPS   "GLON+GPS"
#define TXT_MENU_NAV_GNSS_ALL       "все"

#define TXT_MENU_NAV_MODEL              "dyn-Модель"
#define TXT_MENU_NAV_MODEL_PORTABLE     "PORT"
#define TXT_MENU_NAV_MODEL_STATIONARY   "STATION"
#define TXT_MENU_NAV_MODEL_PEDESTRIAN   "PEDES"
#define TXT_MENU_NAV_MODEL_AUTOMOTIVE   "AUTOMO"
#define TXT_MENU_NAV_MODEL_SEA          "SEA"
#define TXT_MENU_NAV_MODEL_AIRBORN_1G   "AIR<1G"
#define TXT_MENU_NAV_MODEL_AIRBORN_2G   "AIR<2G"
#define TXT_MENU_NAV_MODEL_AIRBORN_4G   "AIR<4G"
#define TXT_MENU_NAV_MODEL_WRISTWORN    "WRIST"
#define TXT_MENU_NAV_MODEL_BIKE         "BIKE"

#define TXT_MENU_NAV_FIXMODE        "Fix-режим"
#define TXT_MENU_NAV_FIXMODE_AUTO   "авто"
#define TXT_MENU_NAV_FIXMODE_2D     "2D"
#define TXT_MENU_NAV_FIXMODE_3D     "3D"

#define TXT_MENU_BTNDO_UP           "Кнопка Вверх"
#define TXT_MENU_BTNDO_DOWN         "Кнопка Вниз"
#define TXT_MENU_BTNDO_NO           "не исп."
#define TXT_MENU_BTNDO_BACKLIGHT    "Подсветка"
#define TXT_MENU_BTNDO_NAVTGL       "Нав: вкл/выкл"
#define TXT_MENU_BTNDO_TRKREC       "Запись трека"
#define TXT_MENU_BTNDO_POWEROFF     "Выкл. питание"

#define TXT_MENU_TRACK_RECORDING    "Писать сейчас"
#define TXT_MENU_TRACK_FORCE        "Вручную"
#define TXT_MENU_TRACK_AUTO         "Автоматически"
#define TXT_MENU_TRACK_NOREC        "выкл"
#define TXT_MENU_TRACK_BYALT        "Автозапись на высоте"
#define TXT_MENU_TRACK_COUNT        "Кол-во треков"
#define TXT_MENU_TRACK_AVAIL        "Доступно для записи"
#define TXT_MENU_TRACK_AVAILSEC     "%d с"

#define TXT_MENU_TIME_ZONE          "Час. пояс"

#define TXT_MENU_OPTION_DISPLAY     "Дисплей"
#define TXT_MENU_OPTION_GNDCORRECT  "Подст. уровня земли"
#define TXT_MENU_OPTION_AUTOSCREEN  "Автоперекл. экрана"
#define TXT_MENU_OPTION_AUTOPOWER   "Автовыключение"
#define TXT_MENU_OPTION_AUTONAV     "Режим Навигации"
#define TXT_MENU_OPTION_COMPEN      "Использовать Компас"
#define TXT_MENU_OPTION_TXTCOURSE   "Курс числом"
#define TXT_MENU_OPTION_BTNDO       "Функции кнопок"
#define TXT_MENU_OPTION_TRACK       "Трэк"
#define TXT_MENU_OPTION_TIME        "Часы"

#define TXT_MENU_FW_VERSION         "Версия прошивки"
#define TXT_MENU_FW_TYPE            "Тип прошивки"
#define TXT_MENU_FW_HWREV           "Аппарат. вер."
#define TXT_MENU_FW_UPDATETO        "Обновить до:"
#define TXT_MENU_FW_NOUPD           "-нет-"
#define TXT_MENU_FW_SDCARD          "Обновить c SD карты"

#define TXT_MENU_SYSNAV_SERIAL      "Direct serial"
#define TXT_MENU_SYSNAV_SATINFO     "Cпутники"
#define TXT_MENU_SYSNAV_VERINFO     "Версия ПО"
#define TXT_MENU_SYSNAV_COLDRST     "Холодный перезапуск"
#define TXT_MENU_SYSNAV_RSTFAIL     "Ошибка перезапуска"
#define TXT_MENU_SYSNAV_RSTOK       "Перезапущено"

#define TXT_MENU_TEST_CLOCK         "Часы"
#define TXT_MENU_TEST_BATTERY       "Батарея"
#define TXT_MENU_TEST_BATTCHARGE    "Подкл. зарядка"
#define TXT_MENU_TEST_PRESSURE      "Давление"
#define TXT_MENU_TEST_PRESSVAL      "(%0.0fкПа) %s"
#define TXT_MENU_TEST_LIGHT         "Подсветка"
#define TXT_MENU_TEST_COMPASS       "Компас"
#define TXT_MENU_TEST_COMPVAL       "(%d) %s"
#define TXT_MENU_TEST_NAVDATA       "Нав: данные"
#define TXT_MENU_TEST_DATADELAY     "(%d мс) %s"
#define TXT_MENU_TEST_NONAVDATA     "нет данных"
#define TXT_MENU_TEST_NAVRESTART    "Нав: Перезапустить"
#define TXT_MENU_TEST_NAVRESTARTED  "Нави перезапущен"
#define TXT_MENU_TEST_NAVINIT       "Нав:Инициализир."
#define TXT_MENU_TEST_NAVINITED     "Нави переинициализирован"
#define TXT_MENU_TEST_SDCART        "SD карта"

#define TXT_MENU_SYSTEM_RESTART     "Перезагрузка"
#define TXT_MENU_SYSTEM_FACTORYRES  "Сброс всех настроек"
#define TXT_MENU_SYSTEM_FORMATROM   "Форматирование"
#define TXT_MENU_SYSTEM_EEPROMFAIL  "Ошибка EEPROM"
#define TXT_MENU_SYSTEM_CFGRESETED  "Настройки сброшены"
#define TXT_MENU_SYSTEM_FWUPDATE    "Обновление прошивки"
#define TXT_MENU_SYSTEM_NAVIGATION  "Модуль навигации"
#define TXT_MENU_SYSTEM_FILES       "Файлы"
#define TXT_MENU_SYSTEM_HWTEST      "Тестирование аппарат."
#define TXT_MENU_SYSTEM_MAGCALIB    "Калибровка магнетом."

#define TXT_MENU_WIFICLI_NET        "Сеть"
#define TXT_MENU_WIFICLI_CONNECTED  "Подключено"
#define TXT_MENU_WIFICLI_USED       "Используется"
#define TXT_MENU_WIFICLI_STOP       "Выключить"
#define TXT_MENU_WIFICLI_STOPPED    "Остановлено"

#define TXT_MENU_NET_BLUETOOTH      "Bluetooth"
#define TXT_MENU_NET_WIFICLI        "Приложение по WiFi"
#define TXT_MENU_NET_WIFISERVER     "На сервер по WiFi"
#define TXT_NET_AUTH_TITLE          "Авторизация в приложении"
#define TXT_NET_AUTH_TEXT1          "Кто-то к вам подключился"
#define TXT_NET_AUTH_TEXT2          "и ему нужен этот код:"
#define TXT_NET_AUTH_WAIT           "Время ожидания: % 2d:%02d"

#define TXT_MENU_ROOT_NAVPOINT      "NAVI точки"
#define TXT_MENU_ROOT_JUMPCOUNT     "Кол-во прыжков"
#define TXT_MENU_ROOT_LOGBOOK       "LogBook"
#define TXT_MENU_ROOT_OPTIONS       "Параметры"
#define TXT_MENU_ROOT_SYSTEM        "Система"
#define TXT_MENU_ROOT_NETSYNC       "Синхронизация"

#define TXT_MENU_ROOT               "Настройки"

#define TXT_SERVER_DNSFAIL          "ошибка адреса сервера"
#define TXT_SERVER_LOST             "потеря связи с сервером"
#define TXT_SERVER_READFAIL         "ошибка при получении данных"
#define TXT_SERVER_PROTOFAIL        "ошибка протокола передачи"
#define TXT_SERVER_SENDFAIL         "ошибка при передаче данных"
#define TXT_SERVER_SENDTIMEOUT      "зависла отправка данных"

#define TXT_WIFI_CONNECTTONET       "Подключение к %s"
#define TXT_WIFI_WEBSYNC            "Web Sync"
#define TXT_WIFI_NET                "WiFi"
#define TXT_WIFI_STATUS_OFF         "WiFi откл."
#define TXT_WIFI_STATUS_DISCONNECT  "WiFi не подкл."
#define TXT_WIFI_STATUS_FAIL        "Ошибка WiFi"
#define TXT_WIFI_WAITJOIN           "Ожидаем привязки"
#define TXT_WIFI_WAIT_SEC           "%d сек"
#define TXT_WIFI_RSSI               "%3d dBm"
#define TXT_WIFI_SEARCHNET          "... поиск сетей ..."
#define TXT_WIFI_NEEDPASSWORD       "Требуется пароль!"

#define TXT_WIFI_MSG_WIFIINIT       "WiFi инициализация..."
#define TXT_WIFI_MSG_WIFICONNECT    "WiFi подключение..."
#define TXT_WIFI_MSG_SRVCONNECT     "Соединение с сервером..."
#define TXT_WIFI_MSG_SRVAUTH        "Авторизация на сервере..."
#define TXT_WIFI_MSG_SENDCONFIG     "Отправка настроек..."
#define TXT_WIFI_MSG_SENDJUMPCOUNT  "Отправка кол-ва прыжков..."
#define TXT_WIFI_MSG_SENDPOINT      "Отправка точек..."
#define TXT_WIFI_MSG_SENDLOGBOOK    "Отправка прыжков..."
#define TXT_WIFI_MSG_SENDTRACK      "Отправка треков..."
#define TXT_WIFI_MSG_SENDFIN        "Завершение отправки..."
#define TXT_WIFI_MSG_JOINACCEPT     "Привязка к Web завершена"
#define TXT_WIFI_MSG_USERCANCEL     "Отменено пользователем"

#define TXT_WIFI_NEXT_HELLO         "Ожидание ответа сервера"
#define TXT_WIFI_NEXT_CONFIRM       "Ожидание подтверждения..."
#define TXT_WIFI_NEXT_RCVPASS       "Приём паролей WiFi"
#define TXT_WIFI_NEXT_RCVFWVER      "Приём версий прошивки"
#define TXT_WIFI_NEXT_FWUPDATE      "Обновление прошивки"
#define TXT_WIFI_NEXT_FIN           "Ожидание завершения..."

#define TXT_WIFI_ERR_WIFIINIT       "Ошибка инициализации WiFi"
#define TXT_WIFI_ERR_WIFICONNECT    "Ошибка подключения WiFi"
#define TXT_WIFI_ERR_WIFITIMEOUT    "Ошибка ожидания wifi"
#define TXT_WIFI_ERR_TIMEOUT        "Ошибка ожидания (таймаут)"
#define TXT_WIFI_ERR_JOINLOAD       "Ошибка чтения Web-привязки"
#define TXT_WIFI_ERR_SENDDATA       "Ошибка отправки данных"
#define TXT_WIFI_ERR_SENDAUTH       "Ошибка авторизации"
#define TXT_WIFI_ERR_SENDCONFIG     "Ошибка отправки настроек"
#define TXT_WIFI_ERR_SENDJUMPCOUNT  "Ошибка отправки кол-ва прыжков"
#define TXT_WIFI_ERR_SENDPOINT      "Ошибка отправки точек"
#define TXT_WIFI_ERR_SENDLOGBOOK    "Ошибка отправки прыжков"
#define TXT_WIFI_ERR_SENDTRACK      "Ошибка отправки треков"
#define TXT_WIFI_ERR_SENDFIN        "Ошибка завершения отправки"
#define TXT_WIFI_ERR_SERVERCONNECT  "Ошибка подключения к серверу"
#define TXT_WIFI_ERR_SRVDISCONNECT  "Связь прервалась"
#define TXT_WIFI_ERR_RCVDATA        "Ошибка при получении данных"
#define TXT_WIFI_ERR_RCVCMDUNKNOWN  "Получена неизвестная команда"
#define TXT_WIFI_ERR_SAVEJOIN       "Ошибка сохранеиня Web-привязки"
#define TXT_WIFI_ERR_SENDJOIN       "Ошибка отправки Web-привязки"
#define TXT_WIFI_ERR_WORKER         "Ошибка подпроцесса"
#define TXT_WIFI_ERR_PASSCLEAR      "Ошибка сброса WiFi-паролей"
#define TXT_WIFI_ERR_PASSCREATE     "Ошибка иниц. WiFi-паролей"
#define TXT_WIFI_ERR_PASSADD        "Ошибка добавления WiFi-паролей"
#define TXT_WIFI_ERR_VERAVAILCLEAR  "Ошибка сброса версий прошивки"
#define TXT_WIFI_ERR_VERAVAILCREATE "Ошибка иниц. версий прошивки"
#define TXT_WIFI_ERR_VERAVAILADD    "Ошибка добавления версий прош."
#define TXT_WIFI_ERR_FWSIZEBIG      "Слишком большой размер прошивки"
#define TXT_WIFI_ERR_FWINIT         "Ошибка инициализации прошивки"
#define TXT_WIFI_ERR_FWWRITE        "Ошибка установки прошивки"
#define TXT_WIFI_ERR_FWFIN          "Ошибка завершения прошивки"

#define TXT_WIFI_SYNCFINISHED       "Синхронизация успешно завершена"

#define TXT_FWSD_TITLE              "Обновление ПО с SD карты"
#define TXT_FWSD_ERR_FILEOPEN       "Не могу открыть файл"
#define TXT_FWSD_ERR_FILEREAD       "Ошибка чтения файла"
#define TXT_FWSD_ERR_MD5            "Ошибка MD5"
#define TXT_FWSD_ERR_FWSIZEBIG      "Слишком большой размер прошивки"
#define TXT_FWSD_ERR_FWINIT         "Ошибка инициализации прошивки"
#define TXT_FWSD_ERR_FWWRITE        "Ошибка установки прошивки"
#define TXT_FWSD_ERR_FWFIN          "Ошибка завершения прошивки"
#define TXT_FWSD_ERR_CANCEL         "Отменено"

#define TXT_BKPSD_ALL               "Резерв всего на SD-карту"
#define TXT_BKPSD_LAST              "Крайний прыг на SD-карту"
#define TXT_BKPSD_FINISH            "Копирование завершено"
#define TXT_BKPSD_ERR_SDINIT        "Ошибка SD-карты"
#define TXT_BKPSD_ERR_MKDIR         "Не могу создать папку"
#define TXT_BKPSD_ERR_FILECREATE    "Не могу создать файл"
#define TXT_BKPSD_ERR_FILEREAD      "Ошибка чтения"
#define TXT_BKPSD_ERR_FILEWRITE     "Ошибка записи"

#define TXT_MCAL_SAVE               "Для Сохранения - длинное наж."
#define TXT_MCAL_SAVED              "Калибровка СОХРАНЕНА!"
#define TXT_MCAL_SIDE180_1          "На противоположную"
#define TXT_MCAL_SIDE180_2          "сторону"
#define TXT_MCAL_MINFRAME_1         "Минимизируйте"
#define TXT_MCAL_MINFRAME_2         "прямоугольник!"

#define TXT_LOGBOOK_JUMPNUM         "Прыжок # %d"
#define TXT_LOGBOOK_ALTEXIT         "Отделение"
#define TXT_LOGBOOK_ALTCNP          "Раскрытие"
#define TXT_LOGBOOK_TIMETOFF        "Длит. взлёта"
#define TXT_LOGBOOK_TIMEFF          "Длит. своб.п."
#define TXT_LOGBOOK_TIMESEC         "%d с"
#define TXT_LOGBOOK_TIMECNP         "Длит. пилотир"

#define TXT_MAIN_VERTSPEED          "%.0f км/ч"
#define TXT_MAIN_NAVSTATE_OFF       "выкл"
#define TXT_MAIN_NAVSTATE_INIT      "иниц"
#define TXT_MAIN_NAVSTATE_INITFAIL  "ош.иниц."
#define TXT_MAIN_NAVSTATE_NODATA    "нет данных"
#define TXT_MAIN_NAVSTATE_SATCOUNT  "%d"
#define TXT_MAIN_NAVSTATE_CRS       "крс:"
#define TXT_MAIN_NAVSTATE_PNT       "тчк:"

#define TXT_MAIN_VSPEED_MS          "%0.1f м/с"
#define TXT_MAIN_3DSPEED_MS         "%0.1f м/с"

#endif // _view_text_lang_H
