#include "devinfo.h"
#include <QBluetoothUuid>

DevInfo::DevInfo(const QBluetoothDeviceInfo &bt)
{
    m_type = SRC_BLUETOOTH;
    m_bt = bt;
}

DevInfo::DevInfo(const WifiDeviceItem &wf)
{
    m_type = SRC_WIFI;
    m_wifi = wf;
    emit changed();
}

QString DevInfo::getAddress() const
{
    switch (m_type) {
        case SRC_BLUETOOTH:
#ifdef Q_OS_MAC
            // On OS X and iOS we do not have addresses,
            // only unique UUIDs generated by Core Bluetooth.
            return m_bt.deviceUuid().toString();
#else
            return m_bt.address().toString();
#endif

        case SRC_WIFI:
            return m_wifi.ip.toString();

        default:
            return "";
    }
}

QString DevInfo::getName() const
{
    switch (m_type) {
        case SRC_BLUETOOTH:
            return m_bt.name();

        case SRC_WIFI:
            return m_wifi.name;

        default:
            return "";
    }
}

void DevInfo::set(const QBluetoothDeviceInfo &bt)
{
    m_type = SRC_BLUETOOTH;
    m_bt = bt;
    emit changed();
}

void DevInfo::set(const WifiDeviceItem &wf)
{
    m_type = SRC_WIFI;
    m_wifi = wf;
    emit changed();
}
